		Shadowbox.init({
			adapter: "base",
			language: "en",
			players: ["img","swf"],
			animate: true,
			animateFade: true,
			animSequence: "sync",
			autoDimensions: false,
			modal: false,
			showOverlay: true,
			overlayColor: "#333",
			overlayOpacity: 0.9,
			flashBgColor: "#000000",
			autoplayMovies: true,
			showMovieControls: true,
			slideshowDelay: 0,
			resizeDuration: 0.3,
			fadeDuration: 0.3,
			viewportPadding: 50,
			displayNav: true,
			continuous: false,
			displayCounter: true,
			counterType: "default",
			counterLimit: 10,
			viewportPadding: 20,
			handleOversize: "resize",
			handleUnsupported: "link",
			initialHeight: 160,
			initialWidth: 320,
			enableKeys: true,
			skipSetup: false,
			flashParams: {bgcolor:"#000000", allowFullScreen:true},
			flashVars: {},
			flashVersion: "9.0.0",
			useSizzle: false
		});
